# Generated by Django 5.2.4 on 2025-07-23 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=150, unique=True)),
                ('mot_de_passe', models.CharField(blank=True, max_length=255, null=True)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('commercial', 'Commercial'), ('partenaire', 'Partenaire'), ('client', 'Client'), ('directeur_commercial', 'Directeur Commercial'), ('responsable_site', 'Responsable Site'), ('proprietaire', 'Propriétaire')], max_length=50)),
                ('permissions', models.JSONField(default=dict)),
                ('actif', models.BooleanField(default=True)),
                ('contact', models.CharField(blank=True, max_length=150, null=True)),
                ('pays', models.CharField(blank=True, max_length=150, null=True)),
                ('ville', models.CharField(blank=True, max_length=150, null=True)),
                ('picture', models.TextField(blank=True, null=True)),
                ('last_connexion', models.DateTimeField(auto_now=True)),
                ('icone', models.CharField(blank=True, max_length=50, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'utilisateurs',
                'indexes': [models.Index(fields=['role'], name='idx_utilisateurs_role')],
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('date_upload', models.DateTimeField(auto_now_add=True)),
                ('id_utilisateur_partenaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='partenaire.utilisateur')),
            ],
            options={
                'db_table': 'image',
            },
        ),
        migrations.CreateModel(
            name='Display',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.TextField()),
                ('localisation', models.TextField(blank=True, null=True)),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('id_utilisateur_partenaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='displays', to='partenaire.utilisateur')),
            ],
            options={
                'db_table': 'display',
            },
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_name', models.TextField()),
                ('status', models.CharField(choices=[('upload', 'Upload'), ('pending', 'Pending'), ('submitted', 'Submitted'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='upload', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('id_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='partenaire.image')),
                ('id_utilisateur_createur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_campaigns', to='partenaire.utilisateur')),
            ],
            options={
                'db_table': 'campaign',
            },
        ),
        migrations.CreateModel(
            name='CampaignDisplay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut_affichage', models.DateField(blank=True, null=True)),
                ('date_fin_affichage', models.DateField(blank=True, null=True)),
                ('nombre_affichages', models.IntegerField(default=0)),
                ('id_campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partenaire.campaign')),
                ('id_display', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partenaire.display')),
            ],
            options={
                'db_table': 'campaignDisplay',
                'indexes': [models.Index(fields=['date_debut_affichage', 'date_fin_affichage'], name='idx_campaign_displays_dates')],
                'constraints': [models.CheckConstraint(condition=models.Q(('date_fin_affichage__isnull', True), ('date_debut_affichage__lte', models.F('date_fin_affichage')), _connector='OR'), name='check_display_dates')],
                'unique_together': {('id_campaign', 'id_display')},
            },
        ),
        migrations.CreateModel(
            name='CampaignImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordre_affichage', models.IntegerField(default=1)),
                ('id_campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partenaire.campaign')),
                ('id_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partenaire.image')),
            ],
            options={
                'db_table': 'campaignImage',
                'unique_together': {('id_campaign', 'id_image')},
            },
        ),
        migrations.CreateModel(
            name='Revenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revenue', models.DecimalField(decimal_places=2, max_digits=12)),
                ('source', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_revenue', models.DateField(auto_now_add=True)),
                ('id_campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='partenaire.campaign')),
                ('id_display', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='partenaire.display')),
                ('id_utilisateur_partenaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='revenues', to='partenaire.utilisateur')),
            ],
            options={
                'db_table': 'revenue',
                'indexes': [models.Index(fields=['date_revenue'], name='idx_revenue_date')],
            },
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['status'], name='idx_campaign_status'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['start_date', 'end_date'], name='idx_campaign_dates'),
        ),
        migrations.AddConstraint(
            model_name='campaign',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__isnull', True), ('start_date__lte', models.F('end_date')), _connector='OR'), name='check_campaign_dates'),
        ),
    ]
